[tools]
ruby = "4.0"

[tasks]
update = "bundle outdated && bundle update && bundle update --bundler"
update-tools = "pre-commit autoupdate"
pre = "pre-commit run --all-files"
lint = "bundle exec rubocop"
test = "bundle exec rspec"
